const String employeeList = "Employee List";
const String addEmployeeDetails = "Add Employee Details";
const String employeeName = "Employee Name";
const String selectRole = "Select Role";
const String today = "Today";
const String noDate = "No Date";
const String cancel = "Cancel";
const String save = "Save";
const String nextMonday = "Next Monday";
const String nextTuesday = "Next Tuesday";
const String after1Week = "After 1 week";
const String errorWhileRequesting = "Error while processing your request";
const String fillRequiredInfo = "Provide all the required information";
const String employeeDataDeleted = "Employee data has been deleted";
const String undo = "Undo";
const String curEmp = "Current employees";
const String prevEmp = "Previous employees";

const List<String> roleList = ["Product Designer", "Flutter Developer", "QA Tester", "Product Owner"];